### ISSUE TITLE
github abap tip

### ISSUE THREAD

**Issue by larshp** [willhogan11/ABAP_Examples#1]
Hi,
If you rename the ".cbl" files to ".abap", then Github will recognize the repository as ABAP code, and the syntax highlighting should also work better

**Comment by willhogan11** [comment]
Hi, 
Thanks for the feedback. The reason for this was because there is no _.abap_ file extention on notepad++ and _.cbl_ gave the most acurate syntax highlighting from the available language list. You are correct that changing now will be better from a GitHub perspective. Thanks.
